import Head from "next/head";
import { Inter } from "next/font/google";
import { useEffect, useState } from "react";
import { Product } from "@/declarations";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [products, setProducts] = useState<Product[]>([]);

  useEffect(() => {
    const fetchProducts = async () => {
      try {
        const res = await fetch('http://localhost:3000/api/products');
        const data: Product[] = await res.json();
        setProducts(data);
      }catch (error) {
        console.error('Error fetching products:', error);
      }
    };

    fetchProducts();
  }, [])

  return (
    <>
      <Head>
        <title>Products Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div>
          <h1>Products</h1>
          <ul>
            {
              products.map((product) => (
                <li key={product.id}>{product.title}</li>
              ))
            }
          </ul>
        </div>
      </main>
    </>
  );
}
